/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedClaimsRouteImport } from './routes/_authenticated/claims'
import { Route as AuthenticatedContractsRouteImport } from './routes/_authenticated/contracts'
import { Route as AuthenticatedCustomersRouteImport } from './routes/_authenticated/customers'
import { Route as AuthenticatedEstimatesRouteImport } from './routes/_authenticated/estimates'
import { Route as AuthenticatedJobsRouteImport } from './routes/_authenticated/jobs'
import { Route as AuthenticatedPipelineRouteImport } from './routes/_authenticated/pipeline'
import { Route as AuthenticatedProductionRouteImport } from './routes/_authenticated/production'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as AuthenticatedLeadsIndexRouteImport } from './routes/_authenticated/leads.index'
import { Route as AuthenticatedLeadsLeadIdRouteImport } from './routes/_authenticated/leads.$leadId'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClaimsRoute = AuthenticatedClaimsRouteImport.update({
  id: '/claims',
  path: '/claims',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContractsRoute = AuthenticatedContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCustomersRoute = AuthenticatedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEstimatesRoute = AuthenticatedEstimatesRouteImport.update({
  id: '/estimates',
  path: '/estimates',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJobsRoute = AuthenticatedJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPipelineRoute = AuthenticatedPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProductionRoute = AuthenticatedProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeadsIndexRoute = AuthenticatedLeadsIndexRouteImport.update({
  id: '/leads/',
  path: '/leads/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeadsLeadIdRoute =
  AuthenticatedLeadsLeadIdRouteImport.update({
    id: '/leads/$leadId',
    path: '/leads/$leadId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/claims': typeof AuthenticatedClaimsRoute
  '/contracts': typeof AuthenticatedContractsRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/estimates': typeof AuthenticatedEstimatesRoute
  '/jobs': typeof AuthenticatedJobsRoute
  '/pipeline': typeof AuthenticatedPipelineRoute
  '/production': typeof AuthenticatedProductionRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/leads/$leadId': typeof AuthenticatedLeadsLeadIdRoute
  '/leads/': typeof AuthenticatedLeadsIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/claims': typeof AuthenticatedClaimsRoute
  '/contracts': typeof AuthenticatedContractsRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/estimates': typeof AuthenticatedEstimatesRoute
  '/jobs': typeof AuthenticatedJobsRoute
  '/pipeline': typeof AuthenticatedPipelineRoute
  '/production': typeof AuthenticatedProductionRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/': typeof AuthenticatedIndexRoute
  '/leads/$leadId': typeof AuthenticatedLeadsLeadIdRoute
  '/leads': typeof AuthenticatedLeadsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/claims': typeof AuthenticatedClaimsRoute
  '/_authenticated/contracts': typeof AuthenticatedContractsRoute
  '/_authenticated/customers': typeof AuthenticatedCustomersRoute
  '/_authenticated/estimates': typeof AuthenticatedEstimatesRoute
  '/_authenticated/jobs': typeof AuthenticatedJobsRoute
  '/_authenticated/pipeline': typeof AuthenticatedPipelineRoute
  '/_authenticated/production': typeof AuthenticatedProductionRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/leads/$leadId': typeof AuthenticatedLeadsLeadIdRoute
  '/_authenticated/leads/': typeof AuthenticatedLeadsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/calendar'
    | '/claims'
    | '/contracts'
    | '/customers'
    | '/estimates'
    | '/jobs'
    | '/pipeline'
    | '/production'
    | '/tasks'
    | '/leads/$leadId'
    | '/leads/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/calendar'
    | '/claims'
    | '/contracts'
    | '/customers'
    | '/estimates'
    | '/jobs'
    | '/pipeline'
    | '/production'
    | '/tasks'
    | '/'
    | '/leads/$leadId'
    | '/leads'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/calendar'
    | '/_authenticated/claims'
    | '/_authenticated/contracts'
    | '/_authenticated/customers'
    | '/_authenticated/estimates'
    | '/_authenticated/jobs'
    | '/_authenticated/pipeline'
    | '/_authenticated/production'
    | '/_authenticated/tasks'
    | '/_authenticated/'
    | '/_authenticated/leads/$leadId'
    | '/_authenticated/leads/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/claims': {
      id: '/_authenticated/claims'
      path: '/claims'
      fullPath: '/claims'
      preLoaderRoute: typeof AuthenticatedClaimsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contracts': {
      id: '/_authenticated/contracts'
      path: '/contracts'
      fullPath: '/contracts'
      preLoaderRoute: typeof AuthenticatedContractsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers': {
      id: '/_authenticated/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estimates': {
      id: '/_authenticated/estimates'
      path: '/estimates'
      fullPath: '/estimates'
      preLoaderRoute: typeof AuthenticatedEstimatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jobs': {
      id: '/_authenticated/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof AuthenticatedJobsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pipeline': {
      id: '/_authenticated/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof AuthenticatedPipelineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/production': {
      id: '/_authenticated/production'
      path: '/production'
      fullPath: '/production'
      preLoaderRoute: typeof AuthenticatedProductionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leads/': {
      id: '/_authenticated/leads/'
      path: '/leads'
      fullPath: '/leads/'
      preLoaderRoute: typeof AuthenticatedLeadsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leads/$leadId': {
      id: '/_authenticated/leads/$leadId'
      path: '/leads/$leadId'
      fullPath: '/leads/$leadId'
      preLoaderRoute: typeof AuthenticatedLeadsLeadIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedClaimsRoute: typeof AuthenticatedClaimsRoute
  AuthenticatedContractsRoute: typeof AuthenticatedContractsRoute
  AuthenticatedCustomersRoute: typeof AuthenticatedCustomersRoute
  AuthenticatedEstimatesRoute: typeof AuthenticatedEstimatesRoute
  AuthenticatedJobsRoute: typeof AuthenticatedJobsRoute
  AuthenticatedPipelineRoute: typeof AuthenticatedPipelineRoute
  AuthenticatedProductionRoute: typeof AuthenticatedProductionRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedLeadsLeadIdRoute: typeof AuthenticatedLeadsLeadIdRoute
  AuthenticatedLeadsIndexRoute: typeof AuthenticatedLeadsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedClaimsRoute: AuthenticatedClaimsRoute,
  AuthenticatedContractsRoute: AuthenticatedContractsRoute,
  AuthenticatedCustomersRoute: AuthenticatedCustomersRoute,
  AuthenticatedEstimatesRoute: AuthenticatedEstimatesRoute,
  AuthenticatedJobsRoute: AuthenticatedJobsRoute,
  AuthenticatedPipelineRoute: AuthenticatedPipelineRoute,
  AuthenticatedProductionRoute: AuthenticatedProductionRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedLeadsLeadIdRoute: AuthenticatedLeadsLeadIdRoute,
  AuthenticatedLeadsIndexRoute: AuthenticatedLeadsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
