revoke all on function public.update_updated_at_column() from public, anon, authenticated;
revoke all on function public.handle_new_user() from public, anon, authenticated;
revoke all on function public.has_role(uuid, public.app_role) from public, anon;
revoke all on function public.has_any_role(uuid, public.app_role[]) from public, anon;
revoke all on function public.can_manage() from public, anon;
revoke all on function public.can_edit() from public, anon;
revoke all on function public.can_view_finance() from public, anon;
revoke all on function public.can_view_all_leads() from public, anon;
grant execute on function public.has_role(uuid, public.app_role) to authenticated;
grant execute on function public.has_any_role(uuid, public.app_role[]) to authenticated;
grant execute on function public.can_manage() to authenticated;
grant execute on function public.can_edit() to authenticated;
grant execute on function public.can_view_finance() to authenticated;
grant execute on function public.can_view_all_leads() to authenticated;